import {Injectable} from '@angular/core';

/** One Font Awesome icon as listed in assets/font-awesome/icons.json (generated by scripts/fa-icons.js). */
export interface FaIcon {
    /** icon name, e.g. "house" */
    n: string;
    /** free styles available: "solid" | "regular" | "brands" */
    s: string[];
    /** human label */
    l: string;
    /** search terms and aliases, lower case */
    t: string[];
}

/** A pickable (icon, style) pair with its ready-to-use class string. */
export interface FaIconOption {
    icon: FaIcon;
    style: string;
    cls: string;
}

export type FaStyle = 'solid' | 'regular' | 'brands';

export const FA_STYLES: FaStyle[] = ['solid', 'regular', 'brands'];

/**
 * Color classes the picker can append to an icon ("fa fa-house icon-red"). They are ordinary global CSS
 * classes defined in styles/erupt.less, so a stored icon stays a plain class list that renders anywhere
 * without being parsed. `css` is only used to paint the swatch and the preview inside the picker.
 */
export interface IconColor {
    cls: string;
    css: string;
}

export const ICON_COLORS: IconColor[] = [
    {cls: 'icon-primary', css: 'var(--ant-primary-color, #1677ff)'},
    {cls: 'icon-blue', css: '#1890ff'},
    {cls: 'icon-cyan', css: '#13c2c2'},
    {cls: 'icon-green', css: '#52c41a'},
    {cls: 'icon-gold', css: '#faad14'},
    {cls: 'icon-orange', css: '#fa8c16'},
    {cls: 'icon-red', css: '#f5222d'},
    {cls: 'icon-magenta', css: '#eb2f96'},
    {cls: 'icon-purple', css: '#722ed1'},
    {cls: 'icon-grey', css: '#8c8c8c'}
];

/** Splits a stored icon class list into the icon part and the color class it carries, if any */
export function splitIconColor(value: string): { icon: string; color: IconColor | null } {
    const tokens = (value || '').trim().split(/\s+/).filter(Boolean);
    const color = ICON_COLORS.find(c => tokens.includes(c.cls)) || null;
    return {icon: tokens.filter(t => t !== color?.cls).join(' '), color};
}

/**
 * Loads the Font Awesome catalogue once per page. The catalogue is derived from the installed
 * @fortawesome/fontawesome-free package at build time, so the framework never maintains an icon list of its own.
 */
@Injectable({providedIn: 'root'})
export class FaIconService {

    private static readonly URL = 'assets/font-awesome/icons.json';

    private loading: Promise<FaIconOption[]> | null = null;

    version = '';

    load(): Promise<FaIconOption[]> {
        if (!this.loading) {
            // plain fetch: this is a static asset, not an erupt API, so it stays out of the API interceptor
            this.loading = fetch(FaIconService.URL).then(res => {
                if (!res.ok) throw new Error(`${FaIconService.URL} ${res.status}`);
                return res.json();
            }).then((data: { version: string; icons: FaIcon[] }) => {
                this.version = data.version;
                const options: FaIconOption[] = [];
                for (const icon of data.icons) {
                    for (const style of icon.s) options.push({icon, style, cls: FaIconService.className(icon.n, style)});
                }
                return options;
            }).catch(err => {
                this.loading = null;
                throw err;
            });
        }
        return this.loading;
    }

    /**
     * Class string erupt renders with: solid keeps the historical "fa fa-name" spelling used throughout menus,
     * the other styles use their explicit family class.
     */
    static className(name: string, style: string): string {
        return style === 'solid' ? `fa fa-${name}` : `fa-${style} fa-${name}`;
    }

    /** Case-insensitive match on name, label, search terms and aliases. */
    static matches(opt: FaIconOption, keyword: string): boolean {
        if (!keyword) return true;
        const icon = opt.icon;
        return icon.n.includes(keyword) || icon.l.toLowerCase().includes(keyword) || icon.t.some(t => t.includes(keyword));
    }
}
